// images
import blogImg1 from "../images/blog/img-10.jpg";
import blogImg2 from "../images/blog/img-11.jpg";
import blogImg3 from "../images/blog/img-12.jpg";

import blogSingleImg1 from "../images/blog/img-10.jpg";
import blogSingleImg2 from "../images/blog/img-11.jpg";
import blogSingleImg3 from "../images/blog/img-12.jpg";

import lifstyle1 from '../images/lifestyle/img-1.jpg' 
import lifstyle2 from '../images/lifestyle/img-2.jpg' 
import lifstyle3 from '../images/lifestyle/img-3.jpg' 

import Food1 from '../images/foods/img-1.jpg' 
import Food2 from '../images/foods/img-2.jpg' 
import Food3 from '../images/foods/img-3.jpg' 

import Business1 from '../images/business/img-1.jpg' 
import Business2 from '../images/business/img-2.jpg' 
import Business3 from '../images/business/img-3.jpg' 



const Blogs = [
    {
        id: '1',
        title: 'Visiting Bethany Beyond the Jordan: Where Jesus was Baptized',
        slug:"Visiting-Bethany",
        screens: blogImg1,
        thumb:'Fasion',
        description: 'You can customize the view Blog posts with a simple mouse click and immediately see the result of your changes.',
        author: 'Marilou Kelleher',
        authorTitle:'Sineor Consultant',
        create_at: '25 Dec, 2023',
        blogSingleImg:blogSingleImg1, 
        comment:'35',
        blClass:'format-standard-image',
    },
    {
        id: '2',
        title: 'Tips From Successful Small Business Owners',
        slug:"Tips-From-Successful",
        thumb:'Fasion',
        author: 'Konal Biry',
        authorTitle:'Creative Director',
        create_at: '13 Dec,2022',
        comment:'80',
        blClass:'format-standard',
    },
    {
        id: '3',
        title: 'Top Five Things to do in Gerome, Cappadocia, Turkey',
        slug:"Turkey",
        screens: blogImg2,
        thumb:'Travel',
        description: 'Consectetur adipiscing elit. Purusout phasellus malesuada lectus.',
        author: 'Aliza',
        authorTitle:'Art Director',
        create_at: '22 Dec,2022',
        blogSingleImg:blogSingleImg2,
        comment:'95',
        blClass:'format-standard-image',
    },
    {
        id: '4',
        title: '10 Reasons Why You Need To Visit Turkey',
        slug:"10-Reasons",
        screens: blogImg3,
        thumb:'Fasion',
        description: 'You can customize the view Blog posts with a simple mouse click and immediately see the result of your changes.',
        author: 'Marilou Kelleher',
        authorTitle:'Sineor Consultant',
        create_at: '25 Dec, 2023',
        blogSingleImg:blogSingleImg3, 
        comment:'35',
        blClass:'format-video',
    },
    {
        id: '5',
        title: 'A Sunday night routine for a great start to the week',
        slug:"A-Sunday-night-routine",
        screens: lifstyle1,
        thumb:'Fasion',
        description: 'You can customize the view Blog posts with a simple mouse click and immediately see the result of your changes.',
        author: 'Marilou Kelleher',
        authorTitle:'Sineor Consultant',
        create_at: '25 Dec, 2023',
        blogSingleImg:lifstyle1, 
        comment:'35',
        blClass:'format-standard-image',
    },
    {
        id: '6',
        title: 'Top ways you deal with stress',
        slug:"deal-with-stress",
        thumb:'Fasion',
        author: 'Konal Biry',
        authorTitle:'Creative Director',
        create_at: '13 Dec,2022',
        comment:'80',
        blClass:'format-standard',
    },
    {
        id: '7',
        title: 'The top then things to do in your city or regional area',
        slug:"regional-area",
        screens: lifstyle2,
        thumb:'Travel',
        description: 'Consectetur adipiscing elit. Purusout phasellus malesuada lectus.',
        author: 'Aliza',
        authorTitle:'Art Director',
        create_at: '22 Dec,2022',
        blogSingleImg:lifstyle2,
        comment:'95',
        blClass:'format-standard-image',
    },
    {
        id: '8',
        title: 'Your tips for growing an Instagram account',
        slug:"Instagram-account",
        screens: lifstyle3,
        thumb:'Fasion',
        description: 'You can customize the view Blog posts with a simple mouse click and immediately see the result of your changes.',
        author: 'Marilou Kelleher',
        authorTitle:'Sineor Consultant',
        create_at: '25 Dec, 2023',
        blogSingleImg:lifstyle3, 
        comment:'35',
        blClass:'format-video',
    },
    {
        id: '9',
        title: 'Restaurant-related events locally or internationally.',
        slug:"internationally",
        screens: Food1,
        thumb:'Fasion',
        description: 'You can customize the view Blog posts with a simple mouse click and immediately see the result of your changes.',
        author: 'Marilou Kelleher',
        authorTitle:'Sineor Consultant',
        create_at: '25 Dec, 2023',
        blogSingleImg:Food1, 
        comment:'35',
        blClass:'format-standard-image',
    },
    {
        id: '10',
        title: 'Interview with the kitchen team.',
        slug:"Interview",
        thumb:'Fasion',
        author: 'Konal Biry',
        authorTitle:'Creative Director',
        create_at: '13 Dec,2022',
        comment:'80',
        blClass:'format-standard',
    },
    {
        id: '11',
        title: 'List of best restaurants for a specific occasion',
        slug:"specific-occasion",
        screens: Food2,
        thumb:'Fasion',
        description: 'You can customize the view Blog posts with a simple mouse click and immediately see the result of your changes.',
        author: 'Marilou Kelleher',
        authorTitle:'Sineor Consultant',
        create_at: '25 Dec, 2023',
        blogSingleImg:Food2, 
        comment:'35',
        blClass:'format-standard-image',
    },
    {
        id: '12',
        title: 'Exclusive recipes from restaurants or chefs',
        slug:"Exclusive-recipes",
        screens: Food3,
        thumb:'Travel',
        description: 'Consectetur adipiscing elit. Purusout phasellus malesuada lectus.',
        author: 'Aliza',
        authorTitle:'Art Director',
        create_at: '22 Dec,2022',
        blogSingleImg:Food3,
        comment:'95',
        blClass:'format-video',
    },
    {
        id: '13',
        title: '8 Mistakes Founders Make When Starting a Business.',
        slug:"8-Mistakes-Founders",
        screens: Business1,
        thumb:'Fasion',
        description: 'You can customize the view Blog posts with a simple mouse click and immediately see the result of your changes.',
        author: 'Marilou Kelleher',
        authorTitle:'Sineor Consultant',
        create_at: '25 Dec, 2023',
        blogSingleImg:Business1, 
        comment:'35',
        blClass:'format-standard-image',
    },
    {
        id: '14',
        title: 'Tips From Successful Small Business Owners',
        slug:"Small-Business",
        thumb:'Fasion',
        author: 'Konal Biry',
        authorTitle:'Creative Director',
        create_at: '13 Dec,2022',
        comment:'80',
        blClass:'format-standard',
    },
    {
        id: '15',
        title: 'Worst Ways Small Businesses Waste Money on Marketing',
        slug:"Waste-Money",
        screens: Business2,
        thumb:'Fasion',
        description: 'You can customize the view Blog posts with a simple mouse click and immediately see the result of your changes.',
        author: 'Marilou Kelleher',
        authorTitle:'Sineor Consultant',
        create_at: '25 Dec, 2023',
        blogSingleImg:Business2, 
        comment:'35',
        blClass:'format-standard-image',
    },
    {
        id: '16',
        title: 'Why Choose Management Consulting?',
        slug:"Consulting",
        screens: Business3,
        thumb:'Travel',
        description: 'Consectetur adipiscing elit. Purusout phasellus malesuada lectus.',
        author: 'Aliza',
        authorTitle:'Art Director',
        create_at: '22 Dec,2022',
        blogSingleImg:Business3,
        comment:'95',
        blClass:'format-video',
    },
];
export default Blogs;